pipeline {
    agent any
    stages {
        stage("Build the Image") {
            steps{
                dir("terraform"){
                    sh 'docker build -t registry.dpdk.com/docker-terraform:1.8.2 .'
                }
            }
        }

        stage("Lis images") {
            steps {
                sh 'docker images'
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
