pipeline {
    agent any
    stages {
        stage("Build the Image") {
            steps{
                dir("jenkins"){
                    sh 'docker build -t registry.dpdk.com/docker-jenkins:2.440.2-1 .'
                }
            }
        }

        stage("List images") {
            steps {
                sh 'docker images'
            }
        }

        stage("Docker cleanup") {
            steps {
              sh 'docker volume prune'
              sh "docker rmi $(docker images | grep '<none>' | awk '{print $3}')"
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
