pipeline {
    stages {
        stage("Build the Image") {
            sh 'docker build -t registry.dpdk.com/docker-jenkins:2.440.2-1 .'
        }

        stage("Lis images") {
            sh 'docker images'
        }
    }
}
